// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/

class VideoModelItemsSnippetThumbnailsHigh {
  String? url;
  int? width;
  int? height;

  VideoModelItemsSnippetThumbnailsHigh({
    this.url,
    this.width,
    this.height,
  });
  VideoModelItemsSnippetThumbnailsHigh.fromJson(Map<String, dynamic> json) {
    url = json["url"]?.toString();
    width = json["width"]?.toInt();
    height = json["height"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    data["width"] = width;
    data["height"] = height;
    return data;
  }
}

class VideoModelItemsSnippetThumbnailsMedium {
  String? url;
  int? width;
  int? height;

  VideoModelItemsSnippetThumbnailsMedium({
    this.url,
    this.width,
    this.height,
  });
  VideoModelItemsSnippetThumbnailsMedium.fromJson(Map<String, dynamic> json) {
    url = json["url"]?.toString();
    width = json["width"]?.toInt();
    height = json["height"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    data["width"] = width;
    data["height"] = height;
    return data;
  }
}

class VideoModelItemsSnippetThumbnailsDefault {
  String? url;
  int? width;
  int? height;

  VideoModelItemsSnippetThumbnailsDefault({
    this.url,
    this.width,
    this.height,
  });
  VideoModelItemsSnippetThumbnailsDefault.fromJson(Map<String, dynamic> json) {
    url = json["url"]?.toString();
    width = json["width"]?.toInt();
    height = json["height"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    data["width"] = width;
    data["height"] = height;
    return data;
  }
}

class VideoModelItemsSnippetThumbnails {
  VideoModelItemsSnippetThumbnailsDefault? theDefault;
  VideoModelItemsSnippetThumbnailsMedium? medium;
  VideoModelItemsSnippetThumbnailsHigh? high;

  VideoModelItemsSnippetThumbnails({
    this.theDefault,
    this.medium,
    this.high,
  });
  VideoModelItemsSnippetThumbnails.fromJson(Map<String, dynamic> json) {
    theDefault = (json["default"] != null)
        ? VideoModelItemsSnippetThumbnailsDefault.fromJson(json["default"])
        : null;
    medium = (json["medium"] != null)
        ? VideoModelItemsSnippetThumbnailsMedium.fromJson(json["medium"])
        : null;
    high = (json["high"] != null)
        ? VideoModelItemsSnippetThumbnailsHigh.fromJson(json["high"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (theDefault != null) {
      data["default"] = theDefault!.toJson();
    }
    if (medium != null) {
      data["medium"] = medium!.toJson();
    }
    if (high != null) {
      data["high"] = high!.toJson();
    }
    return data;
  }
}

class VideoModelItemsSnippet {
  String? publishedAt;
  String? channelId;
  String? title;
  String? description;
  VideoModelItemsSnippetThumbnails? thumbnails;
  String? channelTitle;
  String? liveBroadcastContent;
  String? publishTime;

  VideoModelItemsSnippet({
    this.publishedAt,
    this.channelId,
    this.title,
    this.description,
    this.thumbnails,
    this.channelTitle,
    this.liveBroadcastContent,
    this.publishTime,
  });
  VideoModelItemsSnippet.fromJson(Map<String, dynamic> json) {
    publishedAt = json["publishedAt"]?.toString();
    channelId = json["channelId"]?.toString();
    title = json["title"]?.toString();
    description = json["description"]?.toString();
    thumbnails = (json["thumbnails"] != null)
        ? VideoModelItemsSnippetThumbnails.fromJson(json["thumbnails"])
        : null;
    channelTitle = json["channelTitle"]?.toString();
    liveBroadcastContent = json["liveBroadcastContent"]?.toString();
    publishTime = json["publishTime"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["publishedAt"] = publishedAt;
    data["channelId"] = channelId;
    data["title"] = title;
    data["description"] = description;
    if (thumbnails != null) {
      data["thumbnails"] = thumbnails!.toJson();
    }
    data["channelTitle"] = channelTitle;
    data["liveBroadcastContent"] = liveBroadcastContent;
    data["publishTime"] = publishTime;
    return data;
  }
}

class VideoModelItemsId {
  String? kind;
  String? videoId;

  VideoModelItemsId({
    this.kind,
    this.videoId,
  });
  VideoModelItemsId.fromJson(Map<String, dynamic> json) {
    kind = json["kind"]?.toString();
    videoId = json["videoId"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["kind"] = kind;
    data["videoId"] = videoId;
    return data;
  }
}

class VideoModelItems {
  String? kind;
  String? etag;
  VideoModelItemsId? id;
  VideoModelItemsSnippet? snippet;

  VideoModelItems({
    this.kind,
    this.etag,
    this.id,
    this.snippet,
  });
  VideoModelItems.fromJson(Map<String, dynamic> json) {
    kind = json["kind"]?.toString();
    etag = json["etag"]?.toString();
    id = (json["id"] != null) ? VideoModelItemsId.fromJson(json["id"]) : null;
    snippet = (json["snippet"] != null)
        ? VideoModelItemsSnippet.fromJson(json["snippet"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["kind"] = kind;
    data["etag"] = etag;
    if (id != null) {
      data["id"] = id!.toJson();
    }
    if (snippet != null) {
      data["snippet"] = snippet!.toJson();
    }
    return data;
  }
}

class VideoModelPageInfo {
  int? totalResults;
  int? resultsPerPage;

  VideoModelPageInfo({
    this.totalResults,
    this.resultsPerPage,
  });
  VideoModelPageInfo.fromJson(Map<String, dynamic> json) {
    totalResults = json["totalResults"]?.toInt();
    resultsPerPage = json["resultsPerPage"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["totalResults"] = totalResults;
    data["resultsPerPage"] = resultsPerPage;
    return data;
  }
}

class VideoModel {
  String? kind;
  String? etag;
  String? nextPageToken;
  String? regionCode;
  VideoModelPageInfo? pageInfo;
  List<VideoModelItems?>? items;

  VideoModel({
    this.kind,
    this.etag,
    this.nextPageToken,
    this.regionCode,
    this.pageInfo,
    this.items,
  });
  VideoModel.fromJson(Map<String, dynamic> json) {
    kind = json["kind"]?.toString();
    etag = json["etag"]?.toString();
    nextPageToken = json["nextPageToken"]?.toString();
    regionCode = json["regionCode"]?.toString();
    pageInfo = (json["pageInfo"] != null)
        ? VideoModelPageInfo.fromJson(json["pageInfo"])
        : null;
    if (json["items"] != null) {
      final v = json["items"];
      final arr0 = <VideoModelItems>[];
      v.forEach((v) {
        arr0.add(VideoModelItems.fromJson(v));
      });
      items = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["kind"] = kind;
    data["etag"] = etag;
    data["nextPageToken"] = nextPageToken;
    data["regionCode"] = regionCode;
    if (pageInfo != null) {
      data["pageInfo"] = pageInfo!.toJson();
    }
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["items"] = arr0;
    }
    return data;
  }
}
